### ISSUE TITLE
Module doesn't handle split installations

### ISSUE THREAD

**Issue by atarinut** [ncorrare/reportslack#3]
When the slack report runs by default it points at the puppet master for the report location. If you've set up a split installation the reports are actually on the puppet console server so the URL in the report is incorrect.

**Comment by ncorrare** [comment]
Good catch! Let me check if there is a var I can use for the console, rather than the Puppet Master URL

**Comment by ncorrare** [comment]
@atarinut I'm building a new version (0.1.9) with a potential fix. Can you please try it?

**Comment by atarinut** [comment]
Unfortunately the CA (Certificate Authority) runs on a Puppet Master usually so this change does not fix the issue with the console. Running a "puppet config print" on my puppet master I don't see any variables that reference my console server unfortunately.

I'm wondering if an optional 3rd class parameter that lets you set the FQDN of the console might be the way to handle this, letting it default to the built in "server" if its not set.  I don't see any way to determine the console server without querying the puppetdb otherwise.

**Comment by ncorrare** [comment]
Agreed. I'll probably refactor to add an option (using caserver as default). I'm a bit swamped with another project (ncorrare-pe_slack_bot, you might like it when I get the puppet code working). I'll write a PR tomorrow and merge.

Thank you very much for your feedback!

**Comment by ncorrare** [comment]
Implemented in #9
